/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OrderHistoryRouteImport } from './routes/order-history'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as ShopCollectionRouteImport } from './routes/_shop.$collection'
import { Route as ApiPingRouteImport } from './routes/api.ping'
import { Route as ApiRevalidateRouteImport } from './routes/api.revalidate'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ImgSplatRouteImport } from './routes/img.$'
import { Route as ApiOgSplatRouteImport } from './routes/api.og.$'
import { Route as ShopProductsCategoryIndexRouteImport } from './routes/_shop.products.$category.index'
import { Route as ShopProductsCategorySubcategoryIndexRouteImport } from './routes/_shop.products.$category.$subcategory.index'
import { Route as ShopProductsCategorySubcategoryProductRouteImport } from './routes/_shop.products.$category.$subcategory.$product'

const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryRoute = OrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCollectionRoute = ShopCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => ShopRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ImgSplatRoute = ImgSplatRouteImport.update({
  id: '/img/$',
  path: '/img/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSplatRoute = ApiOgSplatRouteImport.update({
  id: '/api/og/$',
  path: '/api/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductsCategoryIndexRoute =
  ShopProductsCategoryIndexRouteImport.update({
    id: '/products/$category/',
    path: '/products/$category/',
    getParentRoute: () => ShopRoute,
  } as any)
const ShopProductsCategorySubcategoryIndexRoute =
  ShopProductsCategorySubcategoryIndexRouteImport.update({
    id: '/products/$category/$subcategory/',
    path: '/products/$category/$subcategory/',
    getParentRoute: () => ShopRoute,
  } as any)
const ShopProductsCategorySubcategoryProductRoute =
  ShopProductsCategorySubcategoryProductRouteImport.update({
    id: '/products/$category/$subcategory/$product',
    path: '/products/$category/$subcategory/$product',
    getParentRoute: () => ShopRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/order': typeof OrderRoute
  '/order-history': typeof OrderHistoryRoute
  '/scan': typeof ScanRoute
  '/$collection': typeof ShopCollectionRoute
  '/api/ping': typeof ApiPingRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/search': typeof ApiSearchRoute
  '/img/$': typeof ImgSplatRoute
  '/api/og/$': typeof ApiOgSplatRoute
  '/products/$category/': typeof ShopProductsCategoryIndexRoute
  '/products/$category/$subcategory/$product': typeof ShopProductsCategorySubcategoryProductRoute
  '/products/$category/$subcategory/': typeof ShopProductsCategorySubcategoryIndexRoute
}
export interface FileRoutesByTo {
  '/order': typeof OrderRoute
  '/order-history': typeof OrderHistoryRoute
  '/scan': typeof ScanRoute
  '/$collection': typeof ShopCollectionRoute
  '/api/ping': typeof ApiPingRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/search': typeof ApiSearchRoute
  '/img/$': typeof ImgSplatRoute
  '/': typeof ShopIndexRoute
  '/api/og/$': typeof ApiOgSplatRoute
  '/products/$category': typeof ShopProductsCategoryIndexRoute
  '/products/$category/$subcategory/$product': typeof ShopProductsCategorySubcategoryProductRoute
  '/products/$category/$subcategory': typeof ShopProductsCategorySubcategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/order': typeof OrderRoute
  '/order-history': typeof OrderHistoryRoute
  '/scan': typeof ScanRoute
  '/_shop/$collection': typeof ShopCollectionRoute
  '/api/ping': typeof ApiPingRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/search': typeof ApiSearchRoute
  '/img/$': typeof ImgSplatRoute
  '/_shop/': typeof ShopIndexRoute
  '/api/og/$': typeof ApiOgSplatRoute
  '/_shop/products/$category/': typeof ShopProductsCategoryIndexRoute
  '/_shop/products/$category/$subcategory/$product': typeof ShopProductsCategorySubcategoryProductRoute
  '/_shop/products/$category/$subcategory/': typeof ShopProductsCategorySubcategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/order'
    | '/order-history'
    | '/scan'
    | '/$collection'
    | '/api/ping'
    | '/api/revalidate'
    | '/api/search'
    | '/img/$'
    | '/api/og/$'
    | '/products/$category/'
    | '/products/$category/$subcategory/$product'
    | '/products/$category/$subcategory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/order'
    | '/order-history'
    | '/scan'
    | '/$collection'
    | '/api/ping'
    | '/api/revalidate'
    | '/api/search'
    | '/img/$'
    | '/'
    | '/api/og/$'
    | '/products/$category'
    | '/products/$category/$subcategory/$product'
    | '/products/$category/$subcategory'
  id:
    | '__root__'
    | '/_shop'
    | '/order'
    | '/order-history'
    | '/scan'
    | '/_shop/$collection'
    | '/api/ping'
    | '/api/revalidate'
    | '/api/search'
    | '/img/$'
    | '/_shop/'
    | '/api/og/$'
    | '/_shop/products/$category/'
    | '/_shop/products/$category/$subcategory/$product'
    | '/_shop/products/$category/$subcategory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  OrderRoute: typeof OrderRoute
  OrderHistoryRoute: typeof OrderHistoryRoute
  ScanRoute: typeof ScanRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ImgSplatRoute: typeof ImgSplatRoute
  ApiOgSplatRoute: typeof ApiOgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history': {
      id: '/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/$collection': {
      id: '/_shop/$collection'
      path: '/$collection'
      fullPath: '/$collection'
      preLoaderRoute: typeof ShopCollectionRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/img/$': {
      id: '/img/$'
      path: '/img/$'
      fullPath: '/img/$'
      preLoaderRoute: typeof ImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$': {
      id: '/api/og/$'
      path: '/api/og/$'
      fullPath: '/api/og/$'
      preLoaderRoute: typeof ApiOgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/products/$category/': {
      id: '/_shop/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof ShopProductsCategoryIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/products/$category/$subcategory/': {
      id: '/_shop/products/$category/$subcategory/'
      path: '/products/$category/$subcategory'
      fullPath: '/products/$category/$subcategory/'
      preLoaderRoute: typeof ShopProductsCategorySubcategoryIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/products/$category/$subcategory/$product': {
      id: '/_shop/products/$category/$subcategory/$product'
      path: '/products/$category/$subcategory/$product'
      fullPath: '/products/$category/$subcategory/$product'
      preLoaderRoute: typeof ShopProductsCategorySubcategoryProductRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopCollectionRoute: typeof ShopCollectionRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductsCategoryIndexRoute: typeof ShopProductsCategoryIndexRoute
  ShopProductsCategorySubcategoryProductRoute: typeof ShopProductsCategorySubcategoryProductRoute
  ShopProductsCategorySubcategoryIndexRoute: typeof ShopProductsCategorySubcategoryIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCollectionRoute: ShopCollectionRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductsCategoryIndexRoute: ShopProductsCategoryIndexRoute,
  ShopProductsCategorySubcategoryProductRoute:
    ShopProductsCategorySubcategoryProductRoute,
  ShopProductsCategorySubcategoryIndexRoute:
    ShopProductsCategorySubcategoryIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  OrderRoute: OrderRoute,
  OrderHistoryRoute: OrderHistoryRoute,
  ScanRoute: ScanRoute,
  ApiPingRoute: ApiPingRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  ApiSearchRoute: ApiSearchRoute,
  ImgSplatRoute: ImgSplatRoute,
  ApiOgSplatRoute: ApiOgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
